-- Executive summaries generated by AI for selected repositories.
-- RLS: users can only read/write their own rows.

create table if not exists public.repo_summaries (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  repo_id bigint not null,
  full_name text not null,
  summary_json jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, repo_id)
);

create index if not exists idx_repo_summaries_user_id on public.repo_summaries(user_id);
create index if not exists idx_repo_summaries_repo_id on public.repo_summaries(repo_id);

alter table public.repo_summaries enable row level security;

drop policy if exists "Users can manage own repo summaries" on public.repo_summaries;
create policy "Users can manage own repo summaries"
  on public.repo_summaries
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Optional: trigger to keep updated_at in sync
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists repo_summaries_updated_at on public.repo_summaries;
create trigger repo_summaries_updated_at
  before update on public.repo_summaries
  for each row execute function public.set_updated_at();
